### API customer

### Create
POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
    "documentNumber": "71991757",
     "email": "yuleralex1@gmail.com",
     "phone": "935426586",
     "birthDate": "1990-01-01"
}

### Get By id
GET http://localhost:8080/api/v1/customers/1

### Get All
GET http://localhost:8080/api/v1/customers

### Update
PUT http://localhost:8080/api/v1/customers/1
Content-Type: application/json

{
  "documentNumber": "71991743",
  "email": "norka.camasita@gmail.com",
  "phone": "935426586",
  "birthDate": "1992-03-02"
}

### Delete
DELETE http://localhost:8080/api/v1/customers/1

