### API customer

### Create
POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
  "documentNumber": "75583362",
  "email": "frank@gmail.com",
  "phone": "935426586",
  "birthDate": "1990-01-01",
  "addresses": [
    {
      "department": "Lima",
      "province": "Lima",
      "district": "San Juan de Lurigancho",
      "address": "Av. Los Ruiseñores 123",
      "street": "Av. Los Ruiseñores",
      "number": "123",
      "reference": "Frente a la comisaria",
      "postalCode": "15000",
      "latitude": "12.000000",
      "longitude": "-77.000000"
    }
  ]
}

### Get By id
GET http://localhost:8080/api/v1/customers/1

### Get All
GET http://localhost:8080/api/v1/customers

### Update
PUT http://localhost:8080/api/v1/customers/1
Content-Type: application/json

{
  "id": 1,
  "documentNumber": "75583362",
  "email": "norka.camasita@gmail.com",
  "phone": "935426586",
  "birthDate": "1992-04-20",
  "addresses": [
    {
      "id": "1",
      "department": "Ancash",
      "province": "Huari",
      "district": "Huari",
      "address": "Av. Los Ruiseñores 123",
      "street": "Av. Los Ruiseñores",
      "number": "128",
      "reference": "Frente a la comisaria",
      "postalCode": "15000",
      "latitude": "12.000000",
      "longitude": "-77.000000"
    }
  ]
}

### Delete
DELETE http://localhost:8080/api/v1/customers/1

