### API loans

###
POST http://localhost:8081/api/v1/loans
Content-Type: application/json

{
  "customerId": 1,
  "amount": 1000,
  "paymentMethod": "monthly",
  "paymentType": "Efectivo",
  "contractDate": "2021-06-01",
  "interestRate": 0.1,
  "status": "Prestado",
  "term": 5,
  "guaranties":[
    {
      "name": "cosa 1",
      "description": "cosa 1",
      "estimatedValue": 34.56 ,
      "status": "1",
      "imageUrl":"imagen1"
    }
  ]
}



###
GET http://localhost:8081/api/v1/loans/1

###
GET http://localhost:8081/api/v1/loans

###
PUT http://localhost:8081/api/v1/loans/1
Content-Type: application/json

  {
    "id": 1,
    "customerId": 1,
    "amount": 1000.0,
    "paymentMethod": "monthly",
    "paymentType": "yape",
    "contractDate": "2021-06-01",
    "interestRate": 0.15,
    "status": "Prestado",
    "term": 3,
    "guaranties": [
      {
        "id": 1,
        "name": "cosa 1",
        "description": "cosa 1",
        "estimatedValue": 34.560000,
        "status": "1",
        "imageUrl": "imagen1"
      }
    ]
  }

###
DELETE http://localhost:8081/api/v1/loans/1

